### ISSUE TITLE
Enhancement: Support Jupyter notebook

### ISSUE THREAD

**Issue by msharmavikram** [paletteml/mlsync#2]
Creating an enhancement request to enable support for the Jupyter notebook. Jupyter notebook is a widely used tool for developing ML projects but tracking with the Jupyter notebook is currently done manually. Automating this can be of significant benefit.

**Comment by kartik-hegde** [comment]
Since MLFlow works with Jupyter Notebook, they are indirectly supported. But, I agree that an example with the Jupyter notebook would be very helpful, especially given the size of the community using them.

**Comment by msharmavikram** [comment]
There are different degrees to which we can enable Jupyter Notebook. The simplistic version is to use an MLflow-based mechanism. However, what I have in mind is an even more versatile solution with the assumption of an ever-changing notebook that keeps updating as the developers add a new piece of code. Here, MLSync tracks the history of these changes and creates a sort of mind map on the reasoning behind these changes and what was the impact of it. In an ideal MLsync world, we should enable tracking via git commit ids, tags marked to determine what PR id or JIRA ID corresponds to what changes and how these changes evolved over time. Personally, I see this as an exceptionally helpful tool when working with large codebases.

**Comment by kartik-hegde** [comment]
I love the idea of "change logs," I can see how it would be super valuable. Do you mind creating a new issue for this? I think this is separate from the Jupyter notebook support and can use more discussion on the structure and details of the change log. I can see this being useful irrespective of where one would run this.
